spring.application.name=gestion

spring.datasource.url={SPRING_DATASOURCE_URL}
spring.datasource.username={SPRING_DATASOURCE_USERNAME}
spring.datasource.password={SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

app.base.url=https://mea7vdk4ln7cceuftujaythjja0odpvs.lambda-url.eu-west-3.on.aws
